name: week1project
on: [workflow_dispatch]
jobs:
  build:
    name: build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Display folder structure
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree -a -L 3
      - name: Build Docker Image
        run: |
          cd Week1/k8s-aks-demo/
          docker compose build

